name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Update App Version
      id: update_version
      run: |
        VERSION=${{ github.ref_name }}
        sed -i '' "s/__version__ = .*/__version__ = '$VERSION'/" tilt_monitor/__init__.py
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Updated version to $VERSION"

    - name: Install dependencies
      id: install_dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Build and package
      id: build_package
      run: python build.py --dmg --include-dmg-license

    - name: Release
      id: release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: ./package/Tilt-Monitor-${{ env.VERSION }}.dmg
        tag_name: ${{ github.ref_name }}
        name: v${{ env.VERSION }}
        body_path: release_notes.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
